function apt = import_apt(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  APT1 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  APT1 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  APT1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  apt1 = importfile("C:\Users\Alireza\OneDrive\ATA\apt.xlsx", "Sheet 1", [3, 28]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jul-2022 05:25:01

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [3, 28];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":E" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["iata", "icao", "elev", "lat", "long"];
opts.VariableTypes = ["categorical", "string", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "icao", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["iata", "icao"], "EmptyFieldRule", "auto");

% Import the data
apt = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":E" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    apt = [apt; tb]; %#ok<AGROW>
end

apt.Properties.RowNames = string(apt.iata);

end